title: Praxis
description: > # this means to ignore newlines until "baseurl:"
  This conference hopes to aid and encourage increased missional praxis in Ireland as we listen to two international leaders who have been helping small communities turn theory into action and practise this mission for over twenty years.
baseurl: "" # the subpath of your site, e.g. /blog
url: "praxismovement.com.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2018_style/img/icon-large.png"

social:
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages'] # list directories here containing pages to be published

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
