title: Praxis
description: > # this means to ignore newlines until "baseurl:"
  A conference reimagining mission for ordinary people · Dublin, Ireland · 10th - 11th May 2019
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://praxismovement.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2018_style/img/icon-large.png"

social:
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages', '_2019_pages'] # list directories here containing pages to be published

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Eventbrite
    icon: ticket
    url: https://www.eventbrite.ie/e/praxis-2019-a-conference-re-imagining-mission-for-ordinary-people-tickets-55635671792
  - title: Facebook
    icon: facebook
    url: https://www.facebook.com
  - title: Twitter
    icon: twitter
    url: https://twitter.com/praxismovement
  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/praxismovement/

# Build settings
markdown: kramdown
permalink: pretty
